[package]
name = "linker"
version = "1.0.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1 
panic = "abort"
