[package]
name = "smfh"
version = "1.0.0"
edition = "2021"


[dependencies]
blake3 = {version = "1.5.5", features = ["mmap"] }
clap = { version = "4.5.26", features = ["derive"] }
color-eyre = "0.6.3"
jwalk = "0.8.1"
log = "0.4.25"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
simplelog = "0.12.2"

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1 
