[package]
name = "linker"
version = "1.0.0"
edition = "2021"


[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
jwalk = "0.8.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
xxhash-rust = { version = "0.8.15", features = ["xxh3", "const_xxh3"] }

[profile.release]
strip = true
opt-level = 3
lto = "fat"
codegen-units = 1 
