
edition = "2024"
style_edition = "2024"

unstable_features = true

format_code_in_doc_comments = true
wrap_comments = true

imports_granularity = "Crate"
group_imports = "One"
imports_indent = "Block"
imports_layout = "Vertical"
reorder_modules = true
reorder_imports = true
